services:
  api:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
    restart: "no"
    networks:
      - fastapi-postgres
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/sql/:/docker-entrypoint-initdb.d/
    networks:
      - fastapi-postgres
    # TODO: Change me to secrets. See:
    # - https://github.com/docker-library/docs/blob/master/postgres/README.md
    # - https://hub.docker.com/_/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: appdb
      POSTGRES_PASSWORD: changeme
    expose:
      - 5432
volumes:
  db-data:
networks:
  fastapi-postgres:
